// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudLab.Data;

namespace StudLab.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StudLab.Model.TableTransportTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AVector");

                    b.Property<string>("BVector");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("NumColumn");

                    b.Property<int>("NumRow");

                    b.Property<string>("Table");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransportTables");
                });

            modelBuilder.Entity("StudLab.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailUser");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudLab.Models.TablesEntities.MatrixOperationTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("NumColumn");

                    b.Property<int>("NumColumnTwo");

                    b.Property<int>("NumRow");

                    b.Property<int>("NumRowTwo");

                    b.Property<string>("Table");

                    b.Property<string>("TableTwo");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MatrixOperationTask");
                });

            modelBuilder.Entity("StudLab.Models.TablesEntities.MultiCriteriaTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("NumColumn");

                    b.Property<int>("NumRow");

                    b.Property<string>("Table");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MultiCriteriaTables");
                });

            modelBuilder.Entity("StudLab.Model.TableTransportTask", b =>
                {
                    b.HasOne("StudLab.Model.User", "User")
                        .WithMany("TransportTables")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StudLab.Models.TablesEntities.MatrixOperationTask", b =>
                {
                    b.HasOne("StudLab.Model.User", "User")
                        .WithMany("MatrixOperationTables")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StudLab.Models.TablesEntities.MultiCriteriaTask", b =>
                {
                    b.HasOne("StudLab.Model.User", "User")
                        .WithMany("MultiCriteriaTables")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
